In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
url = "data/nhanes_2015_2016.csv"
data = pd.read_csv(url);


In [8]:

data["BMXWT"].mean()

np.float64(81.34267560889516)

In [13]:
gender = data["RIAGENDR"];
print(gender)

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64


In [16]:
bird = ["bird","cat","dog","bird"]
data = {"categorical_data":bird};
dataFrame = pd.DataFrame(data)
print(dataFrame)

  categorical_data
0             bird
1              cat
2              dog
3             bird


In [20]:
dfDummies = pd.get_dummies(dataFrame["categorical_data"],prefix="category",dtype="int");

print(dfDummies.values)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]
